---

- name: Ensure download directory is present
  file:
    path: "{{ download_dir }}"
    state: directory

- name: Get NRPE
  get_url:
    url: "{{ nrpeurl }}"
    dest: "{{ download_dir }}/{{ nrpesrc }}.tar.gz"

- name: Unpack NRPE source files
  unarchive:
    src: "{{ download_dir }}/{{ nrpesrc }}.tar.gz"
    dest: "{{ download_dir }}/"
    remote_src: true

- name: Configure NRPE
  command: "./configure  --enable-command-args --with-init-type={{ ansible_service_mgr | replace('sysvinit', 'sysv') }}"
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: "{{ download_dir }}/{{ nrpesrc }}/Makefile"

- name: Make NRPE
  command: make all
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: "{{ download_dir }}/{{ nrpesrc }}/src/nrpe"

- name: Make install
  command: make install
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: /usr/local/nagios/libexec/check_nrpe

- name: Make install-config
  command: make install-config
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: /usr/local/nagios/etc/nrpe.cfg

- name: Update /etc/services file
  blockinfile:
    dest: /etc/services
    block: |
      # Nagios services
      nrpe    5666/tcp

- name: Make service
  command: make install-init
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: "{{ nrpe_init }}"
  notify: restart nrpe

- name: Reload Systemd
  systemd:
    name: nrpe
    daemon_reload: true
  when: ansible_service_mgr == "systemd"

- name: Reload Upstart
  command: initctl reload-configuration
  changed_when: false
  when: ansible_service_mgr == "sysvinit"

- name: Enable NRPE on boot
  service:
    name: nrpe
    enabled: true
