---

- name: Ensure download directory is present
  file:
    path: "{{ download_dir }}"
    state: directory

- name: Get NRPE
  get_url:
    url: "{{ nrpeurl }}"
    dest: "{{ download_dir }}/{{ nrpesrc }}.tar.gz"

- name: Unpack NRPE source files
  unarchive:
    src: "{{ download_dir }}/{{ nrpesrc }}.tar.gz"
    dest: "{{ download_dir }}/"
    remote_src: yes

# See https://github.com/NagiosEnterprises/nrpe/issues/93
- name: Configure NRPE
  shell: ./configure --enable-command-args --with-need-dh=no
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: "{{ download_dir }}/{{ nrpesrc }}/Makefile"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Configure NRPE
  shell: ./configure  --enable-command-args
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: "{{ download_dir }}/{{ nrpesrc }}/Makefile"
  when: ansible_distribution != "CentOS" or ansible_distribution_major_version == "6"

- name: Make NRPE
  shell: make all
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: "{{ download_dir }}/{{ nrpesrc }}/src/check_nrpe"

- name: Update /etc/services file
  blockinfile:
    dest: /etc/services
    block: |
      # Nagios services
      nrpe    5666/tcp

- name: Make service
  shell: make install-init
  args:
    chdir: "{{ download_dir }}/{{ nrpesrc }}"
    creates: "{{ nrpe_init }}"
  notify: restart nrpe

- name: Ensure plugins directory is present
  file:
    path: "{{ plugins_dir }}"
    state: directory

- name: Copy check_nrpe
  copy:
    src: "{{ download_dir }}/{{ nrpesrc }}/src/check_nrpe"
    dest: "{{ plugins_dir }}/check_nrpe"
    remote_src: yes

- name: Reload Systemd
  systemd:
    name: nrpe
    daemon_reload: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 15) or
        (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 8)

- name: Reload SysVinit
  command: update-rc.d nrpe defaults
  changed_when: False
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int < 8

- name: Reload Upstart
  command: initctl reload-configuration
  changed_when: False
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 15


- name: Enable NRPE on boot
  service:
    name: nrpe
    enabled: yes
