---
# tasks file for nagios

- name: Ensure download directory is present
  file: path={{ download_dir }} state=directory

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-family.yml"

- include: setup-redhat-family-prerequisites.yml
  when: ansible_os_family == 'RedHat'

- include: setup-debian-family-prerequisites.yml
  when: ansible_os_family == 'Debian'

- name: Get NRPE
  get_url: url={{ nrpeurl }} dest={{ download_dir }}/{{ nrpesrc }}.tar.gz

- name: Unpack NRPE source files
  shell: cd {{ download_dir }} && tar -xzvf {{ nrpesrc }}.tar.gz creates={{ download_dir }}/{{ nrpesrc }}

- name: Configure NRPE
  shell: cd {{ download_dir }}/{{ nrpesrc }} && ./configure --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu creates={{ download_dir }}/{{ nrpesrc }}/Makefile

- name: Make NRPE
  shell: cd {{ download_dir }}/{{ nrpesrc }} && make all creates={{ download_dir }}/{{ nrpesrc }}/src/check_nrpe

- name: Ensure plugins directory is present
  file: path={{ plugins_dir }} state=directory

- name: Copy check_nrpe
  shell: cp {{ download_dir }}/{{ nrpesrc }}/src/check_nrpe {{ plugins_dir }}/check_nrpe creates={{ plugins_dir }}/check_nrpe
