---

- name: Set allowed_hosts in nrpe.cfg
  lineinfile:
    dest: /usr/local/nagios/etc/nrpe.cfg
    regexp: '^allowed_hosts='
    line: "allowed_hosts={% for host in nrpe_allowed_hosts %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}"

- name: Set dont_blame in nrpe.cfg
  lineinfile:
    dest: /usr/local/nagios/etc/nrpe.cfg
    regexp: '^dont_blame='
    line: "dont_blame={{ nrpe_dont_blame_nrpe }}"
