---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-nrpe-client

  post_tasks:
    - name: Test with check_nrpe
      command: /usr/local/nagios/libexec/check_nrpe -H 127.0.0.1
      failed_when: nrpe_version not in nrpe_test.stdout
      changed_when: false
      register: nrpe_test

    - name: Grab system Logs
      shell: "journalctl -xn || cat /var/log/messages || cat /var/log/syslog"
      environment:
        - PAGER: cat
      changed_when: false
      ignore_errors: true
